package com.ristlitelink.ristlitelink.classes

import com.ristlitelink.ristlitelink.MainActivity

object Constants {
    const  val supplier_data="supplier_data"
    const val Arabic = "ar"
    const val English = "en"

    const val approve_request = "a"
    const val pending_request = "p"
    const val reject_request = "r"

    const val asc = "asc"
    const val desc = "desc"
    const val countryId = "countryId"
    const val createdAt = "createdAt"
    const val poStep = "poStep"
    const val facilityId = "facilityId"
    const val supplierId = "supplierId"

    const val Requested = "09f1be51-a864-ed11-8e91-c81f66dbb27d"
    const val Approved = "a0e0098a-a864-ed11-8e91-c81f66dbb27d"
    const val Rejected = "557c209a-a864-ed11-8e91-c81f66dbb27d"
    const val PartiallyApproved = "48799471-a864-ed11-8e91-c81f66dbb27d"
    const val PO_FILES = "PO_FILES"


    const val OutFromReturn  ="3a66ced5-a864-ed11-8e91-c81f66dbb27d"
    const val OutFromNotReturn  ="791610e9-a864-ed11-8e91-c81f66dbb27d"
    const val FullDay  ="d5e0abf4-a864-ed11-8e91-c81f66dbb27d"
    const val MultiDays  ="b89ae210-a964-ed11-8e91-c81f66dbb27d"
    const val LateDuty  ="2753798a-7b65-ed11-8e91-c81f66dbb27d"
    const val SickLeave  ="a1e12035-e977-ed11-8e91-c81f66dbb27d"
    const val nightShift  ="a1a85f15-216e-ed11-8e91-c81f66dbb27d"

    var MAIN_ACTIVITY_CLASS = MainActivity::class.java

    const val NORMAL_FONT = "Cairo-Regular.ttf"
    const val BOLD_FONT = "Cairo-Bold.ttf"
    const val ICON_AWSM_FONT = "fa_light_300.otf"
    const val ICON_AWSM_BRAND_FONT = "fa-brands-400.ttf"
    const val ICON_OLD_AWSM_FONT = "fontawesome-webfont.ttf"
    const val ICON_MOON_FONT = "icomoon.ttf"
    const val TIME_ZONE = "GMT+3"
    const val Paly_Link = "http://onelink.to/k9h4jf"
    const val NO_CONNECTION = "no connection"
    const val ERROR = "error"
    const val UnAuthorize = "un authorize"
    const val FAIL = "fail"

    const val KEY_MEMBER = "key_member"
    const val KEY_SOCIAL = "KEY_SOCIAL"
    const val KEY_SETTING = "KEY_SETTING"
    const val KEY_ORGANIZATION = "KEY_ORGANIZATION"
    const val KEY_DEPARTMENTS = "KEY_DEPARTMENTS"
    const val KEY_REQUEST_STATUS = "KEY_REQUEST_STATUS"
    const val KEY_LEVEL_TYPE = "KEY_LEVEL_TYPE"
    const val KEY_COUNTRIES = "KEY_COUNTRIES"
    const val KEY_CURRENCY = "KEY_CURRENCY"
    const val KEY_FACLITY = "KEY_FACLITY"

    const val KEY_SLIDER = "KEY_SLIDER"
    const val KEY_BANNER = "KEY_BANNER"
    const val KEY_DINNERS = "KEY_DINNERS"
    const val KEY_MEMBER_LANGUAGE = "key_member_language"
    const val KEY_TOKEN = "KEY_TOKEN"
    const val KEY_LOGIN = "KEY_LOGIN"
    const val KEY_FCM_TOKEN = "KEY_FCM_TOKEN"
    const val KEY_REFRESH_TOKEN = "KEY_REFRESH_TOKEN"
    const val KEY_REQUESTS_TYPE = "KEY_REQUESTS_TYPE"
    const val IS_HRM = "IS_HRM"
    const val statusColor = "statusColor"
    const val KEY_REQUESTS_TITLE_NAME= "KEY_REQUESTS_TITLE_NAME"
    const val deviceType = 0
    const val deviceOs = "android"
    const val TOKEN_PREFIX = "Bearer "
    const val success = "success"
    const val NO_ITEM = "NO_ITEM"
    const val KEY_LOGIN_PREFERANCE = "key_login_preferance"
    const val CAPTURE = "capture"
    const val PICK = "pick"
    const val LOGIN = "LOGIN"
    const val HR_LOGIN = "HR_LOGIN"
    const val REGISTER = "REGISTER"
    const val REQUEST_ID = "REQUEST_ID"
    const val PNG = "PNG"
    const val JPEG = "JPEG"
    const val pdf = ".pdf"
    const val REQUEST_MODEL = "REQUEST_MODEL"
    const val REQUEST_FILE_URL = "REQUEST_FILE_URL"
    const val DOWNLOAD_FILE = "DOWNLOAD_FILE"
    const val FILES = "FILE"
    const val REQUEST_FILE_NAME = "REQUEST_FILE_NAME"
    const val APPROVE = "approve"
    const val REFRESH = "refresh"
    const val UPDATE_DEFAULT = "update_default"
    const val UPDATEItemImage = "updateItemImage"
    const val DeleteImage = "deleteItemImage"
    const val ADD_ITEM = "add_item"
    const val selectImage = "selectImage"
    const val f = "f"
    const val m = "m"
    const val KEY_CART_SIZE = "KEY_CART_SIZE"
    const val KEY_CART_FASTQ_SIZE = "KEY_CART_FASTQ_SIZE"
    const val KEY_CART_FASTQ_Total = "KEY_CART_FASTQ_Total"
    const val KEY_SCAN_AGAIN = "KEY_SCAN_AGAIN"
    const val KEY_SCAN_SOUND = "KEY_SCAN_SOUND"
    const val KEY_URL = "KEY_URL"
    const val KEY_BASE_URL = "KEY_BASE_URL"
    const val KEY_ACCOUNT_TYPE = "KEY_ACCOUNT_TYPE"
   const val KEY_FILE = "KEY_FILE"
    const val DB_TOTAL_POINTS = "db_total_points"
    const val DB_loyal = "db_loyal"
    const val DB_COUPON_SETTINGS = "db_coupon_settings"
    const val CONTRACT_TYPE = "CONTRACT_TYPE"
    const val PO_TYPE = "PO_TYPE"
    const val USER_TYPE = "USER_TYPE"
    const val HRM_TYPE = "HRM_TYPE"
    const val contractFiles = "contractFiles"

}
